minimum_pre_commit_version: 2.13.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe  # needed for parsing CFN
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.gitignore
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.vscode/.*\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            package.json
          )$
      - id: trailing-whitespace
  - repo: https://github.com/ITProKyle/pre-commit-hook-yamlfmt
    rev: v0.2.0
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4']
        files: |
          (?x)^(
            \.github/(?!dependabot).*\.(yaml|yml)|
            \.markdownlint.yml|
            \.pre-commit-config.yaml|
            \.readthedocs.yml
          )$
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-toc
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
