# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    bugs: issue list --label=bug
    create-repo: repo create "$1" --add-readme --disable-wiki
    default-repo-settings: |-
        !gh repo edit \
          --enable-auto-merge \
          --delete-branch-on-merge \
          --enable-auto-merge=false \
          --enable-merge-commit=false \
          --enable-rebase-merge=false \
          --enable-squash-merge && \
        gh label clone finleyfamily/.github --force
    mine: issue list --assignee @me
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
