[global]
# This allows one to hard-code the position of bash.
#   It maybe be useful to set this to avoid having direnv to fail when PATH is being mutated.
# bash_path = ""

# If set to true, `stdin` is disabled (redirected to `/dev/null`) during the `.envrc` evaluation.
disable_stdin = true

# Also look for and load `.env` files on top of the `.envrc` files.
#   If both `.envrc` and `.env` files exist, the .envrc will always be chosen first.
load_dotenv = false

# If set to true, the `.envrc` will be loaded with `set -euo pipefail`.
strict_env = true

# Specify how long to wait before warning the user that the command is taking too long to execute.
warn_timeout = "3000ms"  # 3s

[whitelist]
# If any of the strings in this list are a prefix of an `.envrc` file’s absolute path,
#   that file will be implicitly allowed, regardless of contents or past usage of
#   `direnv allow` or `direnv deny`.
# prefix = []

# Each string can be a directory name or the full path to an `.envrc` file.
#   If a directory name is passed, it will be treated as if it had been passed
#   as itself with `/.envrc` appended. After resolving the filename, each string
#   will be checked for being an exact match with an `.envrc` file’s absolute path.
#   If they match exactly, that `.envrc` file will be implicitly allowed,
#   regardless of contents or past usage of `direnv allow` or `direnv deny`.
exact = [
  "~/repos/gitlab/.envrc",
]
