#! /usr/bin/env bash

# https://github.com/direnv/direnv/wiki/Find-Up-with-Alternates
function find_up_ {
  (
    while true; do
      for v in "${@}"; do
        if [[ -f "${v}" ]]; then
          echo "${PWD}/${v}"
          return 0
        fi
      done

      if [[ "${PWD}" == / ]] || [[ "${PWD}" == // ]]; then
        return 1
      fi

      cd ..
    done
  )
}


# https://github.com/direnv/direnv/wiki/Find-Up-with-Alternates
function read_version_file {
  local file
  file="$(find_up_ "${@}")"

  [[ -z "${file}" ]] && return

  watch_file "${file}"
  ruby -e "puts ARGF.readline" 2> /dev/null "${file}"  # cspell:ignore ARGF
}


# Usage: source_secrets_if_exists
#
# Loads ".secrets", but only if it exists.
#
function source_secrets_if_exists {
  watch_file "./.secrets"
  set -a
  if [[ -f "./.secrets" ]]; then source_env "./.secrets"; fi
  set +a
}


# https://github.com/direnv/direnv/wiki/Node
function use_nvm {
  local version
  version="${1}"

  [[ "${version}" == --auto ]] && version="$(read_version_file .node-version .nvmrc)"
  [[ -z "${version}" ]] && return

  if [[ -e ~/.nvm/nvm.sh ]]; then
    # shellcheck disable=SC1090
    source ~/.nvm/nvm.sh
    nvm use "${version}"
  fi
}
