#!/usr/bin/env bash
#
# Loaded at user login.

emulate sh -c 'source "${HOME}/.profile"'

if [[ "${__FINLEY_OS}" == "darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)";
fi

# pyenv setup
export PYENV_ROOT="${HOME}/.pyenv"  # pyenv install location
if [[ ":${PATH}:" != *":${PYENV_ROOT}/bin:"* ]]; then
  pyenv_bin="${PYENV_ROOT}/bin/pyenv";

  if [[ -e "${pyenv_bin}" ]]; then
    export PATH="${PYENV_ROOT}/bin:${PATH}";  # add pyenv to path
    eval "$("${pyenv_bin}" init --path)";  # add pyenv shims to path
  else
    echo "pyenv not installed - not added to path";
  fi

  unset pyenv_bin;
fi

# nvm setup
export NVM_DIR="$HOME/.nvm"
if [[ "${__FINLEY_OS}" == "darwin" ]]; then
  [ -s "${HOMEBREW_PREFIX}/opt/nvm/nvm.sh" ] && \. "${HOMEBREW_PREFIX}/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm" ] && \. "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
elif [[ "${__FINLEY_OS}" == "linux" ]]; then
  [ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"  # This loads nvm
  [ -s "${NVM_DIR}nvm/etc/bash_completion.d/nvm" ] && \. "${NVM_DIR}/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
fi
