name: On Push



on: push


env:
  NODE_VERSION: '16'  # default node version
  PYTHON_VERSION: 3.9  # default python version when not using a matrix


jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: poetry install -vv
      - uses: pre-commit/action@v2.0.3
  spell-check:
    # There is an official action published by cSpell.
    # v1.1.1 was tested but did not function as desired so we are using the CLI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: make spellcheck
