name: On Push

on: push

env:
  NODE_VERSION: '20'  # default node version

jobs:
  spellcheck:
    # There is an official action published by cSpell.
    # v1.1.1 was tested but did not function as desired so we are using the CLI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: make spellcheck
